config/routes.rb
Rails.application.routes.draw do
  # http is a protocol where we use verbs to interact with URIs.
  # GET 
  # POST
  # PUT
  # PATCH
  # DELETE

  # set up a route for a GET to /wally with a name of wally.
  get 'wally', to: 'demo#wally', as: 'wally'
                # 'controller#action'

  root to: 'demo#welcome' # Name as 'root'
 end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/demo_controller.rb
class DemoController < ApplicationController
  def wally
  end
    #by default will attempt to load the associated view:
  # app/views/demo/wally.html.erb
  
  def welcome
  end
  #now loads app/views/demo/welcome.html.erb
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/demo_helper.rb
module DemoHelper
end

app/views/demo/wally.html.erb
<h2>Hello Wally!</h2>


<p>
	<%= link_to "home Page", root_path %>
</p>

app/views/demo/welcome.html.erb
<h1>Welcome Page!!!</h1>


<p>
	<%= link_to "wally's Page", wally_path %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RoutingDemo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>